project:
  type: website
  resources:
    - audio
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!xtra"
  output-dir: 5000-Project

website:
  title: "DSAN-5000: Project"
  favicon: "assets/gu-logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About Me
      - href: report/report.qmd
        text: Report
      - text: "Technical Details"
        menu: 
          - text: Project Overview
            href: technical-details/project-overview.qmd
          - text: Data Collection
            href: technical-details/data-collection/main.ipynb 
          - text: Data Cleaning
            href: technical-details/data-cleaning/main.ipynb 
          - text: Exploratory Data Analysis
            href: technical-details/eda/main.ipynb 
          - text: Unsupervised Learning
            href: technical-details/unsupervised-learning/main.ipynb 
          - text: Supervised Learning
            href: technical-details/supervised-learning/main.ipynb 
          - text: LLM usage Log
            href: technical-details/llm-usage-log.qmd

format:
  html:
    theme: superhero
    bibliography:   ./assets/references.bib
    csl:  ./assets/nature.csl
    toc: true



