<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.55">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Cleaning – DSAN-5000: Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/gu-logo.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">DSAN-5000: Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../instructions/overview.html"> 
<span class="menu-text">Instructions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../report/report.html"> 
<span class="menu-text">Report</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-technical-details" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Technical details</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-technical-details">    
        <li>
    <a class="dropdown-item" href="../../technical-details/data-collection/main.html">
 <span class="dropdown-text">Data-collection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../technical-details/data-cleaning/main.html">
 <span class="dropdown-text">Data-cleaning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../technical-details/eda/main.html">
 <span class="dropdown-text">Exploratory Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../technical-details/unsupervised-learning/main.html">
 <span class="dropdown-text">Unsupervised Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../technical-details/supervised-learning/main.html">
 <span class="dropdown-text">Supervised Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../technical-details/progress-log.html">
 <span class="dropdown-text">Progress Log</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../technical-details/llm-usage-log.html">
 <span class="dropdown-text">LLM usage Log</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#instructions" id="toc-instructions" class="nav-link active" data-scroll-target="#instructions">Instructions</a>
  <ul class="collapse">
  <li><a href="#suggested-page-structure" id="toc-suggested-page-structure" class="nav-link" data-scroll-target="#suggested-page-structure">Suggested page structure</a></li>
  <li><a href="#general-comments" id="toc-general-comments" class="nav-link" data-scroll-target="#general-comments">General comments:</a></li>
  <li><a href="#what-to-address" id="toc-what-to-address" class="nav-link" data-scroll-target="#what-to-address">What to address</a></li>
  </ul></li>
  <li><a href="#introduction-and-motivation" id="toc-introduction-and-motivation" class="nav-link" data-scroll-target="#introduction-and-motivation">Introduction and Motivation</a></li>
  <li><a href="#overview-of-methods" id="toc-overview-of-methods" class="nav-link" data-scroll-target="#overview-of-methods">Overview of Methods</a></li>
  <li><a href="#code" id="toc-code" class="nav-link" data-scroll-target="#code">Code</a></li>
  <li><a href="#summary-and-interpretation-of-results" id="toc-summary-and-interpretation-of-results" class="nav-link" data-scroll-target="#summary-and-interpretation-of-results">Summary and Interpretation of Results:</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Cleaning</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- After digesting the instructions, you can delete this cell, these are assignment instructions and do not need to be included in your final submission.  -->
<section id="instructions" class="level1">
<h1>Instructions</h1>
<p><code>Note</code>: You should remove these instructions once you have read and understood them. They should not be included in your final submission.</p>
<p><code>Remember:</code> Exactly what do you on this page will be specific you your project and data. Some things might “make more sense” on other pages, depending on your workflow, for example, you might feel that normalization and scaling should be included in a later section, dealing with machine learning, rather than here, that is totally fine. Organize your project in the way that makes the most sense to you.</p>
<section id="suggested-page-structure" class="level2">
<h2 class="anchored" data-anchor-id="suggested-page-structure">Suggested page structure</h2>
<p>Here’s one suggested structure for organizing your technical pages. You can adjust this as needed:</p>
<p><code>Audience</code>:Remember that these are written for a technical audience. Assume they have completed the DSAN program, but would appreciate refreshers of the important concepts.</p>
<ul>
<li><strong>Introduction and Motivation:</strong> Briefly outline your plan. What are you doing on this page, and why? Provide context and explain the goals of your analysis.</li>
<li><strong>Overview of Methods:</strong> Give a concise explanation of the methods used. For example, if using K-Means clustering, describe what it is, how it works, the inputs and outputs, and key hyperparameters.</li>
<li><strong>Code:</strong> Include the code you used to implement your workflow.</li>
<li><strong>Summary and Interpretation of Results:</strong> Summarize your findings, interpret the results, and discuss their technical implications.</li>
</ul>
</section>
<section id="general-comments" class="level2">
<h2 class="anchored" data-anchor-id="general-comments">General comments:</h2>
<ul>
<li><strong>Iterative Process</strong>: Data cleaning is often not a one-time process. As your analysis progresses, you may need to revisit the cleaning phase, and re-run the code, to adjust to new insights or requirements.</li>
<li><strong>Clarity and Reproducibility</strong>: Ensure your documentation is clear and thorough. Others should be able to follow your steps and achieve the same results.</li>
<li><strong>Visualizations</strong>: Use before-and-after visualizations to illustrate the impact of your cleaning steps, making the process more intuitive and transparent.</li>
</ul>
<p>By the end of this phase, your cleaned data should be well-documented and ready for further stages, such as <strong>Exploratory Data Analysis (EDA)</strong> and <strong>Machine Learning</strong>.</p>
</section>
<section id="what-to-address" class="level2">
<h2 class="anchored" data-anchor-id="what-to-address">What to address</h2>
<p>The following is a list of some of the things you should address on this page. This list is not exhaustive, and you should use your judgment to decide what is most relevant to your project.</p>
<p>The <strong>Data Cleaning</strong> page of your portfolio is where you document the process of transforming your raw data into a usable format. Data cleaning is essential for ensuring the quality of your analysis, and this page should serve as a clear and reproducible guide for anyone reviewing your work. It also provides transparency, allowing others to trace the steps you took to prepare your data.</p>
<p>The following is a guide to help you get started with possible thing to address on this page .</p>
<ul>
<li><strong>Description of the Data Cleaning Process</strong>: Explain the steps you took to clean and preprocess the data.</li>
<li><strong>Code Documentation</strong>: Provide the code used in the data cleaning process (link to GitHub or embed the code directly).</li>
<li><strong>Provide examples of data before and after cleaning</strong>: e.g.&nbsp;with df.head() or df.describe()</li>
<li><strong>Raw and Cleaned Data Links</strong>: Ensure your page links to both the original (raw) dataset and the cleaned dataset. (please keep organized and store the cleaned data in <code>data/processed-data</code>, or similar location which doesn’t get synced to GitHub)</li>
</ul>
<p>Possible things to include:</p>
<p><strong>Introduction to Data Cleaning</strong>:</p>
<ul>
<li>Provide a brief explanation of the data cleaning phase, its importance in preparing the data for further analysis (EDA, modeling), and its iterative nature.</li>
<li>Mention that data cleaning may need to be revisited as the project evolves and analysis goals change.</li>
</ul>
<p><strong>Managing Missing Data</strong>:</p>
<ul>
<li><strong>Identify Missing Values</strong>: Explain how you identified missing data and where it occurred.</li>
<li><strong>Handling Missing Data</strong>: Describe how missing values were addressed (e.g., imputation, removal of rows/columns).</li>
<li><strong>Visualize Missing Data</strong>: Include visualizations (e.g., heatmaps) showing missing values before and after handling them.</li>
</ul>
<p><strong>Outlier Detection and Treatment</strong>:</p>
<ul>
<li><strong>Identify Outliers</strong>: Describe the methods you used to detect outliers in the dataset.</li>
<li><strong>Addressing Outliers</strong>: Explain how outliers were treated (e.g., removal, transformation, or retaining them for analysis).</li>
<li><strong>Visualize Outliers</strong>: Use visualizations (e.g., box plots) to show how outliers were managed.</li>
</ul>
<p><strong>Data Type Correction and Formatting</strong>:</p>
<ul>
<li><strong>Review Data Types</strong>: Summarize the types of variables (numerical, categorical, date-time, etc.) and ensure they are correctly formatted.</li>
<li><strong>Transformation</strong>: Document any transformations performed, such as converting date formats, handling categorical variables, or encoding labels.</li>
<li><strong>Impact of Changes</strong>: Briefly explain why these changes were necessary for accurate analysis.</li>
</ul>
<p><strong>Normalization and Scaling</strong>:</p>
<ul>
<li><strong>Data Distribution Analysis</strong>: Check and discuss the distribution of numerical variables (e.g., skewness).</li>
<li><strong>Normalization Techniques</strong>: Describe any normalization or scaling techniques used (e.g., min-max scaling, z-score normalization).</li>
<li><strong>Before-and-After Visualizations</strong>: Provide visualizations comparing the data before and after scaling or normalization.</li>
</ul>
<p><strong>Subsetting the Data</strong>:</p>
<ul>
<li><strong>Data Filtering</strong>: Explain any subsetting or filtering of the data (e.g., selecting quantitative or qualitative columns).</li>
<li><strong>Rationale</strong>: Justify why you chose to work with a particular subset of the data.</li>
</ul>
</section>
</section>
<section id="introduction-and-motivation" class="level1">
<h1>Introduction and Motivation</h1>
<p>With this stage, I will merge and clean the data I collected from the Consumer Expenditure Survey via the U.S. Bureau of Labor Statistics. The data is organized in a cryptic way. For example, data on income, expenses, and individuals’ demographics are separated into multiple csv files each. Within the csv files, there are numerous encoded variables that need to be deciphered via a data dictionary before I can begin selecting the potentially relevant columns. I will do that for each of the relevant csv files so that there will be a clean data file which I can begin to do exploratory data analysis, and eventually unsupervised and supervised learning on.</p>
</section>
<section id="overview-of-methods" class="level1">
<h1>Overview of Methods</h1>
<p>For this portion, I will be utilizing standard data cleaning tasks such as missing value handling, outlier value handling, duplicate removal and filtering for relevant columns. The expense and income data files are presented on a per instance basis. For example, each expense and income payment for each individual are recorded as an item. In order to make it tidy, I will be aggregating based on the individual identifier ‘NEWID’ to get total income and expenses in the given year. Additionally, there will be merging of data frames to form data frames for income, expenses and characteristics.</p>
</section>
<section id="code" class="level1">
<h1>Code</h1>
<p>Provide the source code used for this section of the project here.</p>
<p>If you’re using a package for code organization, you can import it at this point. However, make sure that the <strong>actual workflow steps</strong>—including data processing, analysis, and other key tasks—are conducted and clearly demonstrated on this page. The goal is to show the technical flow of your project, highlighting how the code is executed to achieve your results.</p>
<p>If relevant, link to additional documentation or external references that explain any complex components. This section should give readers a clear view of how the project is implemented from a technical perspective.</p>
<p>Remember, this page is a technical narrative, NOT just a notebook with a collection of code cells, include in-line Prose, to describe what is going on.</p>
<div id="cell-4" class="cell" data-execution_count="418">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load in necessary packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I first handled the survey data from <strong>Pew Research Center’s American Trends Panel Wave 111</strong>. There was a decently large sample size.</p>
<div id="cell-6" class="cell" data-execution_count="419">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in .sav file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>W111_df <span class="op">=</span> pd.read_spss(<span class="st">"../../data/raw-data/ATP_W111.sav"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#print(W111_df.head())</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Disply data frame shape and column titles</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(W111_df.shape)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(W111_df.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(6034, 139)
Index(['QKEY', 'INTERVIEW_START_W111', 'INTERVIEW_END_W111',
       'DEVICE_TYPE_W111', 'LANG_W111', 'XTABLET_W111', 'SHOP18_W111',
       'SHOP19_W111', 'METOO1_W111', 'METOOSUPOE_M1_W111',
       ...
       'F_PARTYLN_FINAL', 'F_PARTYSUM_FINAL', 'F_PARTYSUMIDEO_FINAL',
       'F_INC_SDT1', 'F_REG', 'F_IDEO', 'F_INTFREQ', 'F_VOLSUM', 'F_INC_TIER2',
       'WEIGHT_W111'],
      dtype='object', length=139)</code></pre>
</div>
</div>
<p>First, I start off by cleaning the whitespace.</p>
<div id="cell-8" class="cell" data-execution_count="420">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean and filter  </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove whitespace from column names     </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>W111_df.columns <span class="op">=</span> W111_df.columns.<span class="bu">str</span>.strip()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> W111_df.columns:</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Iterate through each column name and remove the suffix if present</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> col.endswith(<span class="st">"_W111"</span>): <span class="co"># Checks if column title ends with that title</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        new_col_name <span class="op">=</span> col[:<span class="op">-</span><span class="dv">5</span>]  <span class="co"># Remove that part of the name</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>        W111_df <span class="op">=</span> W111_df.rename(columns<span class="op">=</span>{col: new_col_name})</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> col.startswith(<span class="st">"F_"</span>):</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>        new_col_name <span class="op">=</span> col[<span class="dv">2</span>:]  <span class="co"># Remove the first 2 characters</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>        W111_df <span class="op">=</span> W111_df.rename(columns<span class="op">=</span>{col: new_col_name})</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove whitespace from each row in each column if column data type is string</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> W111_df.columns:</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> W111_df[col].dtype <span class="op">==</span> <span class="st">"object"</span>:</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>        W111_df[col] <span class="op">=</span> W111_df[col].<span class="bu">str</span>.strip()</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After referring to the survey’s questionnaire document (included …) to see what each feature (column) refers too, I selected the following to look into.</p>
<div id="cell-10" class="cell" data-execution_count="421">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>W111_columns_keep <span class="op">=</span> [<span class="st">"ONLSHOP1_a"</span>, <span class="st">"ONLSHOP1_b"</span>, <span class="st">"ONLSHOP1_c"</span>, <span class="st">"SHOP4"</span>, <span class="st">"SNSUSE"</span>, <span class="st">"ONLSHOP5"</span>, <span class="st">"MARITAL"</span>, <span class="st">"USR_SELFID"</span>, <span class="st">"AGECAT"</span>, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"GENDER"</span>, <span class="st">"EDUCCAT"</span>, <span class="st">"RACECMB"</span>, <span class="st">"INC_SDT1"</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>W111_df <span class="op">=</span> W111_df[W111_columns_keep]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View column data types</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">print</span>(W111_df.dtypes) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ONLSHOP1_a    category
ONLSHOP1_b    category
ONLSHOP1_c    category
SHOP4         category
SNSUSE        category
ONLSHOP5      category
MARITAL       category
USR_SELFID    category
AGECAT        category
GENDER        category
EDUCCAT       category
RACECMB       category
INC_SDT1      category
dtype: object
None</code></pre>
</div>
</div>
<div id="cell-11" class="cell" data-execution_count="422">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>W111_df.rename(columns<span class="op">=</span>{<span class="st">'age'</span>: <span class="st">'age_years'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-12" class="cell" data-execution_count="423">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for null values per column</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>null_counts <span class="op">=</span> W111_df.isnull().<span class="bu">sum</span>()</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(null_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ONLSHOP1_a     142
ONLSHOP1_b     142
ONLSHOP1_c     142
SHOP4          142
SNSUSE         142
ONLSHOP5      1406
MARITAL          0
USR_SELFID       0
AGECAT           0
GENDER           0
EDUCCAT          0
RACECMB          2
INC_SDT1         0
dtype: int64</code></pre>
</div>
</div>
<div id="cell-13" class="cell" data-execution_count="424">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(W111_df.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['ONLSHOP1_a', 'ONLSHOP1_b', 'ONLSHOP1_c', 'SHOP4', 'SNSUSE', 'ONLSHOP5',
       'MARITAL', 'USR_SELFID', 'AGECAT', 'GENDER', 'EDUCCAT', 'RACECMB',
       'INC_SDT1'],
      dtype='object')</code></pre>
</div>
</div>
<p>Then I moved on to handling the data from the <strong>Consumer Expenditure Survey</strong>. For each of the datasets used from this survey, I had to go through the corresponding data dictionary (stored in an Excel) to select potentially relevant features. We begin with the income data.</p>
<div id="cell-15" class="cell" data-execution_count="425">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  Import data for income</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>income_1_df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/itii232.csv"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>income_2_df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/itii233.csv"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>income_3_df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/itii234.csv"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>income_4_df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/itii241.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-16" class="cell" data-execution_count="426">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine one of the dataframes</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_1_df.describe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;bound method NDFrame.describe of           NEWID  REFMO  REFYR     UCC  PUBFLAG VALUE_  IMPNUM        VALUE
0       5090604      1   2023  900030        2    NaN       1  3169.833300
1       5090604      1   2023  900030        2    NaN       2  3169.833300
2       5090604      1   2023  900030        2    NaN       3  3169.833300
3       5090604      1   2023  900030        2    NaN       4  3169.833300
4       5090604      1   2023  900030        2    NaN       5  3169.833300
...         ...    ...    ...     ...      ...    ...     ...          ...
330445  5366911      5   2023  980071        2    NaN       1   820.250000
330446  5366911      5   2023  980071        2    NaN       2   250.000000
330447  5366911      5   2023  980071        2    NaN       3   100.000000
330448  5366911      5   2023  980071        2    NaN       4   294.666667
330449  5366911      5   2023  980071        2    NaN       5   160.250000

[330450 rows x 8 columns]&gt;</code></pre>
</div>
</div>
<p>Now I filter for the relevant columns in the income dataframes. From the data collection stage, we already know that each of dataframes has 8 columns. We want the following columns: - The variable “NEWID” represent the unique identifier for the survey participant. - The feature ‘UCC’ stands for Universal Classification Code which correpond to goods and services and other things that can be bought or sold. The values under variable “UCC” correspond to items that would increases or decreases to the individuals’ net worth. - The variable “VALUE” indicate the absolute value of the change in net worth. The other 5 variables only represent data reelvant to the survey process so we subset the dataframes for those 3 columns.</p>
<div id="cell-18" class="cell" data-execution_count="427">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>income_columns_keep <span class="op">=</span> [<span class="st">'NEWID'</span>, <span class="st">'UCC'</span>, <span class="st">'VALUE'</span>]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>income_1_df <span class="op">=</span> income_1_df[income_columns_keep]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_1_df.shape)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>income_2_df <span class="op">=</span> income_2_df[income_columns_keep]</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_2_df.shape)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>income_3_df <span class="op">=</span> income_3_df[income_columns_keep]</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_3_df.shape)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>income_4_df <span class="op">=</span> income_4_df[income_columns_keep]</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_4_df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(330450, 3)
(330840, 3)
(322320, 3)
(325200, 3)</code></pre>
</div>
</div>
<p>Next, we want to find the unqiue “UCC” values to see if we have to deal with decreases in net worth.</p>
<div id="cell-20" class="cell" data-execution_count="428">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize list that stores all unique values of 'UCC' column</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>all_UCC_unique <span class="op">=</span> []</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Function that prints the unique values in a particular column and returns the list</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> find_unique_UCC_values(df, column_name, unique_UCC_values):</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  unique_values <span class="op">=</span> df[column_name].unique()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> value <span class="kw">in</span> unique_values:</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> value <span class="kw">not</span> <span class="kw">in</span> all_UCC_unique:</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>        unique_UCC_values.append(value)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>find_unique_UCC_values(income_1_df, <span class="st">'UCC'</span>, all_UCC_unique)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>find_unique_UCC_values(income_2_df, <span class="st">'UCC'</span>, all_UCC_unique)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>find_unique_UCC_values(income_3_df, <span class="st">'UCC'</span>, all_UCC_unique)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>find_unique_UCC_values(income_4_df, <span class="st">'UCC'</span>, all_UCC_unique)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(all_UCC_unique)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[900030, 900170, 900180, 980000, 980071, 800940, 900000, 900160, 900150, 900090, 900190, 900200, 900210, 900120, 900140]</code></pre>
</div>
</div>
<p>By referring to the data dictionary, I found that the “UCC” values are mostly associated with increases, except for 800940 which represents deductions for social security. There is some overlap between them. For example, 980071 represent income after taxes. Here I want to only focus on pre-tax income for simplicity’s sake. Therefore we filter for the following: - 900030: Social Security and railroad retirement income - 900170: Retirement, survivors, disability income - 900180: Interest and dividends - 980000: Income before taxes - 800940: Deductions for Social Security - 900150: Food stamps</p>
<p>The following codes correspond to income that is lumped into 980000: Income before taxes - 900160: Self-employment income - 900000: Wages and salaries - 900090: Supplemental security income - 900190: Net room/rental income - 900200: Royalty, estate, trust income - 900210: Other regular income - 900140: Other income</p>
<div id="cell-22" class="cell" data-execution_count="429">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>income_df_UCC_keep <span class="op">=</span> [<span class="dv">900030</span>, <span class="dv">900170</span>, <span class="dv">900180</span>, <span class="dv">980000</span>, <span class="dv">800940</span>, <span class="dv">900150</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>negation_UCC_value <span class="op">=</span> <span class="dv">800940</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to filter for the 'UCC' values we want and negate if UCC = 800940</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> filter_and_negate(df, negation_ucc):</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filter the DataFrame based on the UCC list</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  filtered_df <span class="op">=</span> df[df[<span class="st">'UCC'</span>].isin(income_df_UCC_keep)]</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Negate the 'VALUE' column for the specific UCC</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  filtered_df.loc[filtered_df[<span class="st">'UCC'</span>] <span class="op">==</span> negation_ucc, <span class="st">'VALUE'</span>] <span class="op">*=</span> <span class="op">-</span><span class="dv">1</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> filtered_df</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the function to the data frames and check the shape </span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>income_1_df <span class="op">=</span> filter_and_negate(income_1_df, negation_UCC_value)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_1_df.shape)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>income_2_df <span class="op">=</span> filter_and_negate(income_2_df, negation_UCC_value)</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_2_df.shape)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>income_3_df <span class="op">=</span> filter_and_negate(income_3_df, negation_UCC_value)</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_3_df.shape)</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>income_4_df <span class="op">=</span> filter_and_negate(income_4_df, negation_UCC_value)</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(income_4_df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(182790, 3)
(182475, 3)
(178470, 3)
(179925, 3)</code></pre>
</div>
</div>
<p>With the cleaned income dataframes, we aggregate each to find the total income per year per individual and merge all the dataframes to get the master income dataframe. Then we remove duplicates and filter outliers. I have decided to only eliminate outliers for this dataframe because I am assuming no one will be spending significantly more than they earn. Therefore, eliminating outliers for the income dataframe should be adequate.</p>
<div id="cell-24" class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function sums income sources based on participant ID </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_total_income(df):</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use reset_index to make a hierarchical index a regular column</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  total_income_df <span class="op">=</span> df.groupby(<span class="st">'NEWID'</span>)[<span class="st">'VALUE'</span>].<span class="bu">sum</span>().reset_index() </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Rename columns in place</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  total_income_df.columns <span class="op">=</span> [<span class="st">'id'</span>, <span class="st">'total_income'</span>]</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> total_income_df</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate total income for each DataFrame</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>total_income_df1 <span class="op">=</span> calculate_total_income(income_1_df)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>total_income_df2 <span class="op">=</span> calculate_total_income(income_2_df)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>total_income_df3 <span class="op">=</span> calculate_total_income(income_3_df)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>total_income_df4 <span class="op">=</span> calculate_total_income(income_4_df)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Concatenate dataframes to get total income per survey participant</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>total_income_df <span class="op">=</span> pd.concat([total_income_df1, total_income_df2, total_income_df3, total_income_df4], axis <span class="op">=</span> <span class="dv">0</span>)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove duplicates based on 'id' column</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>total_income_df.drop_duplicates(subset<span class="op">=</span><span class="st">'id'</span>, keep<span class="op">=</span><span class="st">'first'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove outliers</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate IQR and identify outliers</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>Q1 <span class="op">=</span> total_income_df[<span class="st">'total_income'</span>].quantile(<span class="fl">0.25</span>)</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>Q3 <span class="op">=</span> total_income_df[<span class="st">'total_income'</span>].quantile(<span class="fl">0.75</span>)</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>IQR <span class="op">=</span> Q3 <span class="op">-</span> Q1</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="op">=</span> Q1 <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> IQR</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="op">=</span> Q3 <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> IQR</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out outliers</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>total_income_df <span class="op">=</span> total_income_df[(total_income_df[<span class="st">'total_income'</span>] <span class="op">&gt;=</span> lower_bound) <span class="op">&amp;</span> (total_income_df[<span class="st">'total_income'</span>] <span class="op">&lt;=</span> upper_bound)]</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataframe of income over a year</span></span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_income_df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(17382, 2)</code></pre>
</div>
</div>
<div id="cell-25" class="cell" data-execution_count="431">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_income_df.head)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;bound method NDFrame.head of            id  total_income
0     5090604   101692.5000
1     5090624    34467.5010
2     5090634   155839.9995
3     5090664    72695.0001
4     5090674    43196.2500
...       ...           ...
4673  5607931   222792.4995
4674  5607951    54740.0010
4675  5607961   130770.0000
4677  5608001    84775.0005
4679  5608061    65240.0010

[17382 rows x 2 columns]&gt;</code></pre>
</div>
</div>
<p>Now we handle the expenditures data.</p>
<div id="cell-27" class="cell" data-execution_count="432">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  Import data for expenses</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>expense_1_df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/mtbi232.csv"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>expense_2_df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/mtbi233.csv"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>expense_3_df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/mtbi234.csv"</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>expense_4_df <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/mtbi241.csv"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset expense Data Frames for the relevant columns</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>expense_columns_keep <span class="op">=</span> [<span class="st">'NEWID'</span>, <span class="st">'SEQNO'</span>, <span class="st">'UCC'</span>, <span class="st">'COST'</span>]</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>expense_1_df <span class="op">=</span> expense_1_df[expense_columns_keep]</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>expense_2_df <span class="op">=</span> expense_2_df[expense_columns_keep]</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>expense_3_df <span class="op">=</span> expense_3_df[expense_columns_keep]</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>expense_4_df <span class="op">=</span> expense_4_df[expense_columns_keep]</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>expense_df <span class="op">=</span> pd.concat([expense_1_df, expense_2_df, expense_3_df, expense_4_df], axis <span class="op">=</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By consulting the data dictionary, I located the specific files that listed the online purchases of tangible goods.</p>
<div id="cell-29" class="cell" data-execution_count="433">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import csv files for online purchases</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>specific_expense_df1 <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/apb23.csv"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>specific_expense_df2 <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/eqb23.csv"</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>specific_expense_df3 <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/mis23.csv"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>specific_expense_df4 <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/ovb23.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/sm/dt8s0j7j0glg1jfrlpndm0lw0000gn/T/ipykernel_1037/3622570946.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  specific_expense_df1 = pd.read_csv("../../data/raw-data/apb23.csv")</code></pre>
</div>
</div>
<div id="cell-30" class="cell" data-execution_count="434">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(specific_expense_df1.columns)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(specific_expense_df2.columns)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(specific_expense_df3.columns)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(specific_expense_df4.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['QYEAR', 'NEWID', 'SEQNO', 'ALCNO', 'REC_ORIG', 'MINAPPLY', 'MINA_PLY',
       'GFTCMIN', 'GFTCMIN_', 'MIN_MO', 'MIN_MO_', 'MINPURX', 'MINPURX_',
       'MINRENTX', 'MINR_NTX', 'MNAPPL1', 'MNAPPL1_', 'MNAPPL2', 'MNAPPL2_',
       'MNAPPL3', 'MNAPPL3_', 'MNAPPL4', 'MNAPPL4_', 'MNAPPL5', 'MNAPPL5_',
       'MNAPPL6', 'MNAPPL6_', 'MNAPPL7', 'MNAPPL7_', 'MNAPPL8', 'MNAPPL8_',
       'MNAPPL9', 'MNAPPL9_', 'INSTLSCR', 'INST_SCR', 'INSTLLEX', 'INST_LEX',
       'APBPURCH'],
      dtype='object')
Index(['QYEAR', 'NEWID', 'SEQNO', 'ALCNO', 'REC_ORIG', 'APPRPRYB', 'APPR_RYB',
       'SRVCMOB', 'SRVCMOB_', 'REPAIRX', 'REPAIRX_', 'APPRPB1', 'APPRPB1_',
       'APPRPB2', 'APPRPB2_', 'APPRPB3', 'APPRPB3_', 'APPRPB4', 'APPRPB4_',
       'APPRPB5', 'APPRPB5_', 'APPRPB6', 'APPRPB6_', 'APPRPB7', 'APPRPB7_',
       'APPRPB8', 'APPRPB8_', 'APPRPB9', 'EQBPURCH', 'APPRPB9_'],
      dtype='object')
Index(['QYEAR', 'NEWID', 'SEQNO', 'ALCNO', 'REC_ORIG', 'MISCCODE', 'MISC_ODE',
       'MISCMO', 'MISCMO_', 'MISCGFTC', 'MISC_FTC', 'MISCEXPX', 'MISC_XPX',
       'MISCDE1', 'MISCDE1_', 'MISCDE2', 'MISCDE2_', 'MISCDE3', 'MISCDE3_',
       'MISCDE4', 'MISCDE4_', 'MISCDE5', 'MISCDE5_', 'MISCDE6', 'MISCDE6_',
       'MISCDE7', 'MISCDE7_', 'MISCDE8', 'MISCDE8_', 'MISCDE9', 'MISPURCH',
       'MISCDE9_'],
      dtype='object')
Index(['QYEAR', 'NEWID', 'SEQNO', 'ALCNO', 'REC_ORIG', 'VEHICYB', 'VEHICYB_',
       'VEHICYR', 'VEHICYR_', 'VEHBSNZ', 'VEHBSNZ_', 'VEHNEWU', 'VEHNEWU_',
       'VEHGFTC', 'VEHGFTC_', 'VEHPURMO', 'VEHP_RMO', 'VEHPURYR', 'VEHP_RYR',
       'VFINSTAT', 'VFIN_TAT', 'TRADEX', 'TRADEX_', 'NETPURX', 'NETPURX_',
       'DNPAYMTX', 'DNPA_MTX', 'PRINCIPX', 'PRIN_IPX', 'VEHQPMT', 'VEHQPMT_',
       'PMT1MO', 'PMT1MO_', 'PMT1YR', 'PMT1YR_', 'PAYMENTX', 'PAYM_NTX',
       'QINTRSTZ', 'QINT_STZ', 'QLOANM1Q', 'QLOA_M1Q', 'QBALNM1X', 'QBAL_M1X',
       'QVINTM1X', 'QVIN_M1X', 'QVPRIM1X', 'QVPR_M1X', 'QLOANM2Q', 'QLOA_M2Q',
       'QBALNM2X', 'QBAL_M2X', 'QVINTM2X', 'QVIN_M2X', 'QVPRIM2X', 'QVPR_M2X',
       'QLOANM3Q', 'QLOA_M3Q', 'QBALNM3X', 'QBAL_M3X', 'QVINTM3X', 'QVIN_M3X',
       'QVPRIM3X', 'QVPR_M3X', 'QTRADEX', 'QTRADEX_', 'QREIMBRZ', 'QREI_BRZ',
       'QADITR1X', 'QADI_R1X', 'QADITR2X', 'QADI_R2X', 'QADITR3X', 'QADI_R3X',
       'QDNPYMTX', 'QDNP_MTX', 'VEHEQTLN', 'VEHE_TLN', 'VEHICIB', 'VEHICIB_',
       'MAKE', 'MAKE_', 'OVBPURCH', 'VFINANCE', 'FUELTYPE', 'FUEL_YPE',
       'VPURINDV', 'VPUR_NDV', 'VINTRATE', 'VINT_ATE'],
      dtype='object')</code></pre>
</div>
</div>
<p>Filter the specific purchase Data Frames for the relevant columns so we get four dataframes of online expenses. - ‘SEQNO’ is the identifier variable for the purchases and can be used to merge with expense data frames. - ‘APBPURCH’ tells us if this item was purchased online or in-person.</p>
<div id="cell-32" class="cell" data-execution_count="435">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>apb_columns_keep <span class="op">=</span> [<span class="st">'NEWID'</span>, <span class="st">'SEQNO'</span>, <span class="st">'APBPURCH'</span>]</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>online_expense_df1 <span class="op">=</span> specific_expense_df1[apb_columns_keep]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>online_expense_df1_subset <span class="op">=</span> online_expense_df1.loc[online_expense_df1[<span class="st">'APBPURCH'</span>] <span class="op">==</span> <span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>‘EQBPURCH’ tells us if this item was bought online or in-person.</li>
</ul>
<div id="cell-34" class="cell" data-execution_count="436">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>eqb_columns_keep <span class="op">=</span> [<span class="st">'NEWID'</span>, <span class="st">'SEQNO'</span>, <span class="st">'EQBPURCH'</span>]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>online_expense_df2 <span class="op">=</span> specific_expense_df2[eqb_columns_keep]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>online_expense_df2_subset <span class="op">=</span> online_expense_df2.loc[online_expense_df2[<span class="st">'EQBPURCH'</span>] <span class="op">==</span> <span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>‘MISPURCH’ tells us if this item was bought online or in-person.</li>
</ul>
<div id="cell-36" class="cell" data-execution_count="437">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>mis_columns_keep <span class="op">=</span> [<span class="st">'NEWID'</span>, <span class="st">'SEQNO'</span>, <span class="st">'MISPURCH'</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>online_expense_df3 <span class="op">=</span> specific_expense_df3[mis_columns_keep]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>online_expense_df3_subset <span class="op">=</span> online_expense_df3.loc[online_expense_df3[<span class="st">'MISPURCH'</span>] <span class="op">==</span> <span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>‘OVBPURCH’ tells us if this item was bought online or in-person.</li>
</ul>
<div id="cell-38" class="cell" data-execution_count="438">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>ovb_columns_keep <span class="op">=</span> [<span class="st">'NEWID'</span>, <span class="st">'SEQNO'</span>, <span class="st">'OVBPURCH'</span>]</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>online_expense_df4 <span class="op">=</span> specific_expense_df4[ovb_columns_keep]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>online_expense_df4_subset <span class="op">=</span> online_expense_df4.loc[online_expense_df4[<span class="st">'OVBPURCH'</span>] <span class="op">==</span> <span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we combine the mini-dataframes to get the the online_expense_df which we will merge with the expense_df to see the dollar amount of the online purchase. Then, we aggregate based upon ‘NEWID’ primary key to calculate the total expense per person, total online expense and the online spending percentage.</p>
<div id="cell-40" class="cell" data-execution_count="439">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Concatenate all online expense df</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>online_expense_df <span class="op">=</span> pd.concat([online_expense_df1_subset, online_expense_df2_subset, online_expense_df3_subset, online_expense_df4_subset], axis <span class="op">=</span> <span class="dv">0</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for relevant columns</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>online_expense_df <span class="op">=</span> online_expense_df[[<span class="st">'NEWID'</span>, <span class="st">'SEQNO'</span>]]</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a column with imputed constant values of 1 for later merging so we know the expenses are online </span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>online_expense_df[<span class="st">'Is_Online'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Online Expense Columns: "</span>,online_expense_df.columns)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the two DataFrames based on 'NEWID' and 'SEQNO'</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>merged_expense_df <span class="op">=</span> expense_df.merge(online_expense_df, on<span class="op">=</span>[<span class="st">'NEWID'</span>, <span class="st">'SEQNO'</span>], how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Merged Expense Columns: "</span>, merged_expense_df.columns)</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate total expenses, online expenses, and online percentage for each individual</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by 'NEWID' column, and perform 3 aggregate functions</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>total_expense_df <span class="op">=</span> merged_expense_df.groupby(<span class="st">'NEWID'</span>).agg(</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">id</span><span class="op">=</span>(<span class="st">'NEWID'</span>, <span class="st">'first'</span>),</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">#create a new column, and calculates the sum of 'COST'</span></span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>    Total_Expense<span class="op">=</span>(<span class="st">'COST'</span>, <span class="st">'sum'</span>), </span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>    <span class="co">#filter COST column to include only rows where Is_Online is 1 ( online purchases)</span></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>    Online_Expense<span class="op">=</span>(<span class="st">'COST'</span>, <span class="kw">lambda</span> x: x[merged_expense_df[<span class="st">'Is_Online'</span>] <span class="op">==</span> <span class="dv">1</span>].<span class="bu">sum</span>()), </span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>    <span class="co">#filter COST column for online purchases and claculates that as a % of total</span></span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>    Online_Percentage<span class="op">=</span>(<span class="st">'COST'</span>, <span class="kw">lambda</span> x: x[merged_expense_df[<span class="st">'Is_Online'</span>] <span class="op">==</span> <span class="dv">1</span>].<span class="bu">sum</span>() <span class="op">/</span> x.<span class="bu">sum</span>() <span class="op">*</span> <span class="dv">100</span>)</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a column 'bought_online' to indicate whether the person bought something online</span></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>total_expense_df[<span class="st">'bought_online'</span>] <span class="op">=</span> (total_expense_df[<span class="st">'Online_Expense'</span>] <span class="op">&gt;</span> <span class="dv">0</span>).astype(<span class="bu">int</span>)</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop duplicates</span></span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>total_expense_df.drop_duplicates(subset<span class="op">=</span><span class="st">'id'</span>, keep<span class="op">=</span><span class="st">'first'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total Expense Columns: "</span>, total_expense_df.columns)</span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_expense_df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Online Expense Columns:  Index(['NEWID', 'SEQNO', 'Is_Online'], dtype='object')
Merged Expense Columns:  Index(['NEWID', 'SEQNO', 'UCC', 'COST', 'Is_Online'], dtype='object')
Total Expense Columns:  Index(['id', 'Total_Expense', 'Online_Expense', 'Online_Percentage',
       'bought_online'],
      dtype='object')
(18871, 5)</code></pre>
</div>
</div>
<p>Now we move on to handling characteristics data. This requires a lot of referring to the data dictionary.</p>
<div id="cell-42" class="cell" data-execution_count="440">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data for individual characteristics</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>characteristics_df_1 <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/memi232.csv"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>characteristics_df_2 <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/memi233.csv"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>characteristics_df_3 <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/memi234.csv"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>characteristics_df_4 <span class="op">=</span> pd.read_csv(<span class="st">"../../data/raw-data/memi241.csv"</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for  relevant columns</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>characteristics_columns_keep <span class="op">=</span> [<span class="st">"NEWID"</span>, <span class="st">"AGE"</span>, <span class="st">"ARM_FORC"</span>, <span class="st">"EARNTYPE"</span>, <span class="st">"EDUCA"</span>, <span class="st">"INCWEEKQ"</span>, </span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"INDRETX"</span>, <span class="st">"JSSDEDX"</span>, <span class="st">"JSSDEDXM"</span>, <span class="st">"MARITAL"</span>, <span class="st">"MEMBRACE"</span>, <span class="st">"RC_ASIAN"</span>, <span class="st">"RC_BLACK"</span>, <span class="st">"RC_DK"</span>, <span class="st">"RC_NATAM"</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"RC_OTHER"</span>, <span class="st">"RC_PACIL"</span>, <span class="st">"RC_WHITE"</span>, <span class="st">"SEX"</span>, <span class="st">"SOCRRX"</span>]</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>characteristics_df_1 <span class="op">=</span> characteristics_df_1[characteristics_columns_keep]</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>characteristics_df_2 <span class="op">=</span> characteristics_df_2[characteristics_columns_keep]</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>characteristics_df_3 <span class="op">=</span> characteristics_df_3[characteristics_columns_keep]</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>characteristics_df_4 <span class="op">=</span> characteristics_df_4[characteristics_columns_keep]</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all of them</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>characteristics_df <span class="op">=</span> pd.concat([characteristics_df_1, characteristics_df_2, characteristics_df_3, characteristics_df_4], axis <span class="op">=</span> <span class="dv">0</span>)</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-43" class="cell" data-execution_count="441">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename columns</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>characteristics_df.rename(columns<span class="op">=</span>{<span class="st">"NEWID"</span>: <span class="st">"id"</span>, <span class="st">"AGE"</span>: <span class="st">"age"</span>, <span class="st">"ARM_FORC"</span>: <span class="st">"is_military"</span>,  <span class="st">"EARNTYPE"</span>: <span class="st">"earning_type"</span>, <span class="st">"EDUCA"</span>: <span class="st">"highest_ed_completed"</span>, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"INCWEEKQ"</span>: <span class="st">"num_weeks_worked_in_last_yr"</span>, <span class="st">"INDRETX"</span>: <span class="st">"deposited_money_in_retirement_this_yr"</span>, </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"JSSDEDX"</span>: <span class="st">"income_into_SS_this_yr"</span>, <span class="st">"JSSDEDXM"</span>: <span class="st">"SS_payments_received_this_yr"</span>, <span class="st">"MARITAL"</span>: <span class="st">"marital_status"</span>, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"MEMBRACE"</span>: <span class="st">"race"</span>, <span class="st">"RC_ASIAN"</span>: <span class="st">"is_asian"</span>, <span class="st">"RC_BLACK"</span>: <span class="st">"is_black"</span>, <span class="st">"RC_DK"</span>: <span class="st">"race_unknown"</span>, </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"RC_NATAM"</span>: <span class="st">"is_native_american"</span>, <span class="st">"RC_OTHER"</span>: <span class="st">"is_other_race"</span>, <span class="st">"RC_PACIL"</span>: <span class="st">"is_pacific_islander"</span>, </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"RC_WHITE"</span>: <span class="st">"is_white"</span>, <span class="st">"SEX"</span>: <span class="st">"sex"</span>, <span class="st">"SOCRRX"</span>: <span class="st">"SS_and_railroad_retirement_income_received"</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We need to do some data cleaning for the categorical variables and one-hot encode them.</p>
<div id="cell-45" class="cell" data-execution_count="442">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Data cleaning for one-hot encoding is_military table</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>characteristics_df[<span class="st">"is_military"</span>] <span class="op">=</span> characteristics_df[<span class="st">'is_military'</span>].replace(<span class="dv">2</span>, <span class="dv">0</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode the 'earning_type' column</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>characteristics_df <span class="op">=</span> pd.get_dummies(characteristics_df, columns<span class="op">=</span>[<span class="st">'earning_type'</span>], prefix<span class="op">=</span><span class="st">''</span>, prefix_sep<span class="op">=</span><span class="st">''</span>, dtype <span class="op">=</span> <span class="bu">int</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the earning_type columns</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>characteristics_df.rename(columns<span class="op">=</span>{<span class="st">'1.0'</span>: <span class="st">'full_time_1_yr'</span>, </span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'2.0'</span>: <span class="st">'part_time_1_yr'</span>, </span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'3.0'</span>: <span class="st">'full_time_part_yr'</span>, </span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'4.0'</span>: <span class="st">'part_time_part_yr'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode the 'highest_ed_completed' column</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>characteristics_df <span class="op">=</span> pd.get_dummies(characteristics_df, columns<span class="op">=</span>[<span class="st">'highest_ed_completed'</span>], prefix<span class="op">=</span><span class="st">''</span>, prefix_sep<span class="op">=</span><span class="st">''</span>, dtype <span class="op">=</span> <span class="bu">int</span>)</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the highest_ed_completed columns</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>characteristics_df.rename(columns<span class="op">=</span>{<span class="st">'1.0'</span>: <span class="st">'no_school_completed'</span>, </span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'2.0'</span>: <span class="st">'grades_1-8_completed'</span>, </span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'3.0'</span>: <span class="st">'high_school_no_degree'</span>, </span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'4.0'</span>: <span class="st">'high_school_grad'</span>,</span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'5.0'</span>: <span class="st">'some_college_no_degree'</span>,</span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'6.0'</span>: <span class="st">'associates_degree'</span>,</span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'7.0'</span>: <span class="st">'bachelors_degree'</span>,</span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'8.0'</span>: <span class="st">'graduate_degree'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode the 'marital_status' column</span></span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a>characteristics_df <span class="op">=</span> pd.get_dummies(characteristics_df, columns<span class="op">=</span>[<span class="st">'marital_status'</span>], prefix<span class="op">=</span><span class="st">''</span>, prefix_sep<span class="op">=</span><span class="st">''</span>, dtype <span class="op">=</span> <span class="bu">int</span>)</span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the marital_status columns</span></span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a>characteristics_df.rename(columns<span class="op">=</span>{<span class="st">'1'</span>: <span class="st">'is_married'</span>, </span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'2'</span>: <span class="st">'is_widowed'</span>, </span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'3'</span>: <span class="st">'is_divorced'</span>, </span>
<span id="cb38-34"><a href="#cb38-34" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'4'</span>: <span class="st">'is_separated'</span>,</span>
<span id="cb38-35"><a href="#cb38-35" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'5'</span>: <span class="st">'is_single'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode the 'sex' column</span></span>
<span id="cb38-38"><a href="#cb38-38" aria-hidden="true" tabindex="-1"></a>characteristics_df <span class="op">=</span> pd.get_dummies(characteristics_df, columns<span class="op">=</span>[<span class="st">'sex'</span>], prefix<span class="op">=</span><span class="st">''</span>, prefix_sep<span class="op">=</span><span class="st">''</span>, dtype <span class="op">=</span> <span class="bu">int</span>)</span>
<span id="cb38-39"><a href="#cb38-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-40"><a href="#cb38-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the sex columns</span></span>
<span id="cb38-41"><a href="#cb38-41" aria-hidden="true" tabindex="-1"></a>characteristics_df.rename(columns<span class="op">=</span>{<span class="st">'1'</span>: <span class="st">'is_male'</span>, </span>
<span id="cb38-42"><a href="#cb38-42" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'2'</span>: <span class="st">'is_female'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-46" class="cell" data-execution_count="443">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View values per column about race</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Legend: White - 1, Black - 2, Native American - 3, Asian - 4, Pacific Islander - 5, Other - 6, Unknown - 7</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>race_columns <span class="op">=</span> [<span class="st">"is_asian"</span>, <span class="st">"is_black"</span>, <span class="st">"race_unknown"</span>, <span class="st">"is_native_american"</span>, <span class="st">"is_other_race"</span>, <span class="st">"is_pacific_islander"</span>, <span class="st">"is_white"</span>]</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(characteristics_df[<span class="st">"race"</span>].value_counts())</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> race <span class="kw">in</span> race_columns:</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(characteristics_df[race].value_counts())</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co"># One-Hot Encode Race Columns</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace numerical values for one-hot-encoding</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>characteristics_df[<span class="st">"is_asian"</span>] <span class="op">=</span> characteristics_df[<span class="st">'is_asian'</span>].replace(<span class="dv">4</span>, <span class="dv">1</span>)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>characteristics_df[<span class="st">"is_black"</span>] <span class="op">=</span> characteristics_df[<span class="st">'is_black'</span>].replace(<span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>characteristics_df[<span class="st">"race_unknown"</span>] <span class="op">=</span> characteristics_df[<span class="st">'race_unknown'</span>].replace(<span class="dv">7</span>, <span class="dv">1</span>)</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>characteristics_df[<span class="st">"is_native_american"</span>] <span class="op">=</span> characteristics_df[<span class="st">'is_native_american'</span>].replace(<span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>characteristics_df[<span class="st">"is_other_race"</span>] <span class="op">=</span> characteristics_df[<span class="st">'is_other_race'</span>].replace(<span class="dv">6</span>, <span class="dv">1</span>)</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>characteristics_df[<span class="st">"is_pacific_islander"</span>] <span class="op">=</span> characteristics_df[<span class="st">'is_pacific_islander'</span>].replace(<span class="dv">5</span>, <span class="dv">1</span>)</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace NaN values with 0</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>characteristics_df[race_columns] <span class="op">=</span> characteristics_df[race_columns].fillna(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>race
1    34631
2     4560
4     3405
6     1040
5      259
3      235
Name: count, dtype: int64
is_asian
4.0    3714
Name: count, dtype: int64
is_black
2.0    4784
Name: count, dtype: int64
race_unknown
7.0    297
Name: count, dtype: int64
is_native_american
3.0    432
Name: count, dtype: int64
is_other_race
6.0    2595
Name: count, dtype: int64
is_pacific_islander
5.0    415
Name: count, dtype: int64
is_white
1.0    32913
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-47" class="cell" data-execution_count="444">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(characteristics_df.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['id', 'age', 'is_military', 'num_weeks_worked_in_last_yr',
       'deposited_money_in_retirement_this_yr', 'income_into_SS_this_yr',
       'SS_payments_received_this_yr', 'race', 'is_asian', 'is_black',
       'race_unknown', 'is_native_american', 'is_other_race',
       'is_pacific_islander', 'is_white',
       'SS_and_railroad_retirement_income_received', 'full_time_1_yr',
       'part_time_1_yr', 'full_time_part_yr', 'part_time_part_yr',
       'no_school_completed', 'grades_1-8_completed', 'high_school_no_degree',
       'high_school_grad', 'some_college_no_degree', 'associates_degree',
       'bachelors_degree', 'graduate_degree', 'is_married', 'is_widowed',
       'is_divorced', 'is_separated', 'is_single', 'is_male', 'is_female'],
      dtype='object')</code></pre>
</div>
</div>
<p>Now we merge the total income, expenses, and characteristics dataframe with one another to form the final dataframe, ces_df.</p>
<div id="cell-49" class="cell" data-execution_count="450">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>ces_df <span class="op">=</span> total_expense_df.merge(total_income_df, on<span class="op">=</span><span class="st">'id'</span>, how<span class="op">=</span><span class="st">'inner'</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>ces_df <span class="op">=</span> ces_df.merge(characteristics_df, on<span class="op">=</span><span class="st">'id'</span>,how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ces_df.columns)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ces_df.head)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['id', 'Total_Expense', 'Online_Expense', 'Online_Percentage',
       'bought_online', 'total_income', 'age', 'is_military',
       'num_weeks_worked_in_last_yr', 'deposited_money_in_retirement_this_yr',
       'income_into_SS_this_yr', 'SS_payments_received_this_yr', 'race',
       'is_asian', 'is_black', 'race_unknown', 'is_native_american',
       'is_other_race', 'is_pacific_islander', 'is_white',
       'SS_and_railroad_retirement_income_received', 'full_time_1_yr',
       'part_time_1_yr', 'full_time_part_yr', 'part_time_part_yr',
       'no_school_completed', 'grades_1-8_completed', 'high_school_no_degree',
       'high_school_grad', 'some_college_no_degree', 'associates_degree',
       'bachelors_degree', 'graduate_degree', 'is_married', 'is_widowed',
       'is_divorced', 'is_separated', 'is_single', 'is_male', 'is_female'],
      dtype='object')
&lt;bound method NDFrame.head of             id  Total_Expense  Online_Expense  Online_Percentage  \
0      5090604  184019.000000             0.0                0.0   
1      5090604  184019.000000             0.0                0.0   
2      5090624    4616.000000             0.0                0.0   
3      5090634  150661.999999             0.0                0.0   
4      5090664   57142.999999             0.0                0.0   
...        ...            ...             ...                ...   
39906  5607961   13624.000000             0.0                0.0   
39907  5607961   13624.000000             0.0                0.0   
39908  5607961   13624.000000             0.0                0.0   
39909  5608001   12992.000000             0.0                0.0   
39910  5608061   58554.000000             0.0                0.0   

       bought_online  total_income  age  is_military  \
0                  0   101692.5000   74          NaN   
1                  0   101692.5000   72          NaN   
2                  0    34467.5010   87          NaN   
3                  0   155839.9995   58          0.0   
4                  0    72695.0001   55          0.0   
...              ...           ...  ...          ...   
39906              0   130770.0000   77          NaN   
39907              0   130770.0000   64          0.0   
39908              0   130770.0000   43          0.0   
39909              0    84775.0005   37          0.0   
39910              0    65240.0010   67          NaN   

       num_weeks_worked_in_last_yr  deposited_money_in_retirement_this_yr  \
0                              0.0                                    NaN   
1                              0.0                                    NaN   
2                              0.0                                    NaN   
3                             52.0                                24000.0   
4                             52.0                                 3600.0   
...                            ...                                    ...   
39906                          0.0                                    NaN   
39907                          0.0                                    NaN   
39908                          0.0                                    NaN   
39909                         52.0                                 1000.0   
39910                          0.0                                    NaN   

       ...  associates_degree  bachelors_degree  graduate_degree  is_married  \
0      ...                  0                 0                1           1   
1      ...                  1                 0                0           1   
2      ...                  0                 0                0           0   
3      ...                  0                 1                0           0   
4      ...                  0                 0                0           1   
...    ...                ...               ...              ...         ...   
39906  ...                  0                 0                0           0   
39907  ...                  0                 0                0           0   
39908  ...                  0                 0                0           0   
39909  ...                  0                 0                1           0   
39910  ...                  0                 0                0           0   

       is_widowed  is_divorced  is_separated  is_single  is_male  is_female  
0               0            0             0          0        1          0  
1               0            0             0          0        0          1  
2               0            1             0          0        0          1  
3               0            1             0          0        0          1  
4               0            0             0          0        1          0  
...           ...          ...           ...        ...      ...        ...  
39906           0            1             0          0        1          0  
39907           0            1             0          0        0          1  
39908           0            0             0          1        1          0  
39909           0            0             0          1        0          1  
39910           0            0             1          0        0          1  

[39911 rows x 40 columns]&gt;</code></pre>
</div>
</div>
<p>Check for nulls in each column. After examining the null counts and their respective columns, there seem to be quite a few so we want to impute null values with 0.</p>
<div id="cell-51" class="cell" data-execution_count="451">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ces_df.isnull().<span class="bu">sum</span>())</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co">#print(len(ces_df))</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ces_df[<span class="st">'is_military'</span>].isnull().<span class="bu">sum</span>())</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ces_df[<span class="st">'is_military'</span>].value_counts())</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's impute all null values with 0</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>ces_df <span class="op">=</span> ces_df.fillna(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>id                                                0
Total_Expense                                     0
Online_Expense                                    0
Online_Percentage                                 0
bought_online                                     0
total_income                                      0
age                                               0
is_military                                   15826
num_weeks_worked_in_last_yr                    6067
deposited_money_in_retirement_this_yr         35028
income_into_SS_this_yr                        18855
SS_payments_received_this_yr                  18855
race                                              0
is_asian                                          0
is_black                                          0
race_unknown                                      0
is_native_american                                0
is_other_race                                     0
is_pacific_islander                               0
is_white                                          0
SS_and_railroad_retirement_income_received     6067
full_time_1_yr                                    0
part_time_1_yr                                    0
full_time_part_yr                                 0
part_time_part_yr                                 0
no_school_completed                               0
grades_1-8_completed                              0
high_school_no_degree                             0
high_school_grad                                  0
some_college_no_degree                            0
associates_degree                                 0
bachelors_degree                                  0
graduate_degree                                   0
is_married                                        0
is_widowed                                        0
is_divorced                                       0
is_separated                                      0
is_single                                         0
is_male                                           0
is_female                                         0
dtype: int64
15826
is_military
0.0    23682
1.0      403
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-52" class="cell" data-execution_count="452">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># New null values</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ces_df.isnull().<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>id                                            0
Total_Expense                                 0
Online_Expense                                0
Online_Percentage                             0
bought_online                                 0
total_income                                  0
age                                           0
is_military                                   0
num_weeks_worked_in_last_yr                   0
deposited_money_in_retirement_this_yr         0
income_into_SS_this_yr                        0
SS_payments_received_this_yr                  0
race                                          0
is_asian                                      0
is_black                                      0
race_unknown                                  0
is_native_american                            0
is_other_race                                 0
is_pacific_islander                           0
is_white                                      0
SS_and_railroad_retirement_income_received    0
full_time_1_yr                                0
part_time_1_yr                                0
full_time_part_yr                             0
part_time_part_yr                             0
no_school_completed                           0
grades_1-8_completed                          0
high_school_no_degree                         0
high_school_grad                              0
some_college_no_degree                        0
associates_degree                             0
bachelors_degree                              0
graduate_degree                               0
is_married                                    0
is_widowed                                    0
is_divorced                                   0
is_separated                                  0
is_single                                     0
is_male                                       0
is_female                                     0
dtype: int64</code></pre>
</div>
</div>
<div id="cell-53" class="cell" data-execution_count="455">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ces_df.columns)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ces_df.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['id', 'Total_Expense', 'Online_Expense', 'Online_Percentage',
       'bought_online', 'total_income', 'age', 'is_military',
       'num_weeks_worked_in_last_yr', 'deposited_money_in_retirement_this_yr',
       'income_into_SS_this_yr', 'SS_payments_received_this_yr', 'race',
       'is_asian', 'is_black', 'race_unknown', 'is_native_american',
       'is_other_race', 'is_pacific_islander', 'is_white',
       'SS_and_railroad_retirement_income_received', 'full_time_1_yr',
       'part_time_1_yr', 'full_time_part_yr', 'part_time_part_yr',
       'no_school_completed', 'grades_1-8_completed', 'high_school_no_degree',
       'high_school_grad', 'some_college_no_degree', 'associates_degree',
       'bachelors_degree', 'graduate_degree', 'is_married', 'is_widowed',
       'is_divorced', 'is_separated', 'is_single', 'is_male', 'is_female'],
      dtype='object')
(39911, 40)</code></pre>
</div>
</div>
<div id="cell-54" class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to csv for access in later stages</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>ces_df.to_csv(<span class="st">'../../data/processed-data/ces_clean.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="summary-and-interpretation-of-results" class="level1">
<h1>Summary and Interpretation of Results:</h1>
<p>I ended up with a dataset with the columns as presented above. We have almost 40,000 data records to work with and 40 features which should be more than enough. We have data on total income, total expenses, online shopping expendtiture, wprking information, and demographic details. Based on that, I am able to address the following research questions:</p>
<ol type="1">
<li>How do customer demographics (age, gender, race, education level, income, etc.) influence one’s preference for in-store or online shopping?</li>
<li>What demographic factors predict proportion of online spending among total expenses?</li>
<li>What is the relationship between retirement contributions and shopping preferences?</li>
<li>Can we predict one’s employment type or education level based on how much they spend on online shopping?</li>
</ol>
<p>I want to focus on questions 1, 2 and 4. I believe that question 3 presents an interesting aspect, but individuals who contributing more to retirement contributions are more likely to be old and more financially responsible so there is a lower chance of them spending much via online shopping.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>